### ISSUE TITLE
Arbitrary Code Execution

### ISSUE THREAD

**Issue by aschuster3** [LightshedHealth/imagine#3]
While looking through and testing, I noticed that there are some exec statements within the main file.  Out of curiosity I ran the following command on my test server (host obfuscated for safety reasons)

```sh
curl $APP_HOST:80/capture?type=png&format=string&resource=https://github.com;echo 'hello'
```

What was returned to me was this:

```
[3] 8411
[4] 8412
hello
[4]   Done                    format=string
```

We may want to consider some very prejudice white-listing.

**Comment by aschuster3** [comment]
On second pass through, I realized that 
```sh
curl $APP_HOST:80/capture?type=png&format=string&resource=https://github.com;echo 'hello'
```
is actually running 
```sh
curl $APP_HOST:80/capture?type=png&format=string&resource=https://github.com
echo 'hello'
```
and because curl responds asynchronously, the `hello` is just slapped in there.  Without parsing through logs it's hard to say if I actually did anything and I'm not sure how Javascript parses url encoded semi-colons (semi-colons are actually reserved for URIs, as I just now discovered, so there is a difference between `;` and `%3B`)

**Comment by joedursun** [comment]
While the example you gave may not have worked, you're correct that we're open to arbitrary code execution. For now I'll update the code to whitelist the request path characters to be alphanumeric and '=' only. This should mostly work and will be a quick fix.

For the longer term fix we can add a signature param that encodes a private API key that is set in the app's environment. This way we'll know if the request is coming from a trusted source or not.

**Comment by joedursun** [comment]
[Quick fix in this commit](https://github.com/LightshedHealth/imagine/commit/4871a7726eb5116dbe2b6887bd2bd20dcaa02bde).

I'll start working on a more permanent fix soon.
