### ISSUE TITLE
Denial of Service

### ISSUE THREAD

**Issue by databyte** [LightshedHealth/imagine#4]
I can get it to spin, spin, spin on a query like:

http://service/capture?type=pdf&resource=http://service/capture%3Ftype=pdf%26resource=http://service

**Comment by joedursun** [comment]
Now that we've implemented signed requests, the only way for the above scenario to happen is if you DOS your own server. We could implement a fix for this, but it would be at least a small performance hit. 

Do you think it's still worth fixing or do you think with the new signature param we don't need to worry about it anymore?

**Comment by databyte** [comment]
If the signature isn't valid and you return a `401`, it should be fine then. Now the only question is, what happens if someone tries to bruteforce the signature by making a ton of requests... but I'm sure you'd notice that on the ELB.
